import { describe, expect, it } from 'vitest'
import { createSessionApi, MAX_SESSION_REQUEST_BODY_BYTES } from './session-api'
import { InMemorySessionRepository, SessionService, type SessionRepository, type StoredSession } from '../lib/session-service'

const headers = { authorization: 'Bearer owner', 'content-type': 'application/json' }
const request = (path: string, init: RequestInit = {}) => new Request(`https://example.test${path}`, { ...init, headers: { ...headers, ...init.headers } })
const service = (repository: SessionRepository = new InMemorySessionRepository()) => createSessionApi(new SessionService(repository), { async verify(r) { return r.headers.get('authorization') === 'Bearer owner' ? { ownerId: 'owner' } : r.headers.get('authorization') === 'Bearer other' ? { ownerId: 'other' } : undefined } })
const command = (sessionId = 'acceptance') => ({ protocolVersion: 1, sessionId })
const chunk = (overrides: Record<string, unknown> = {}) => ({ protocolVersion: 1, sessionId: 'acceptance', chunkId: 'chunk', sequence: 0, captureStartMs: 7777, captureEndMs: 8888, mimeType: 'audio/sentinel', byteLength: 1, sha256: 'a'.repeat(64), continuityState: 'observed-continuous', confirmedGaps: [], ...overrides })
const create = (api: ReturnType<typeof service>, value: unknown = command()) => api(request('/api/v1/sessions', { method: 'POST', body: JSON.stringify(value) }))
function secure(response: Response) { expect(response.headers.get('content-type')).toBe('application/json; charset=utf-8'); expect(response.headers.get('cache-control')).toBe('no-store'); expect(response.headers.get('x-content-type-options')).toBe('nosniff'); expect(response.headers.get('referrer-policy')).toBe('no-referrer'); expect(response.headers.get('access-control-allow-origin')).not.toBe('*') }

describe('session API acceptance', () => {
  it('provides exact lifecycle ETags and public bodies, including duplicate invariance', async () => {
    const api = service(); const created = await create(api); expect(created.status).toBe(201); expect(created.headers.get('location')).toBe('/api/v1/sessions/acceptance'); expect(created.headers.get('etag')).toBe('"0"'); expect(await created.json()).toEqual({ data: { protocolVersion: 1, sessionId: 'acceptance', state: 'created', revision: 0, receivedChunkCount: 0, receivedSequences: [], confirmedGapCount: 0, continuitySummary: 'not-observed' } })
    expect((await api(request('/api/v1/sessions/acceptance/start', { method: 'POST', headers: { 'if-match': '"0"' } }))).headers.get('etag')).toBe('"1"')
    const accepted = await api(request('/api/v1/sessions/acceptance/chunks', { method: 'POST', headers: { 'if-match': '"1"' }, body: JSON.stringify(chunk()) })); expect(accepted.status).toBe(200); expect(accepted.headers.get('etag')).toBe('"2"'); expect(JSON.stringify(await accepted.json())).not.toMatch(/audio\/sentinel|7777|8888|aaaa/)
    const duplicate = await api(request('/api/v1/sessions/acceptance/chunks', { method: 'POST', headers: { 'if-match': '"2"' }, body: JSON.stringify(chunk()) })); expect(duplicate.headers.get('etag')).toBe('"2"'); expect(await duplicate.json()).toMatchObject({ data: { disposition: 'duplicate', session: { revision: 2 } } })
    const final = await api(request('/api/v1/sessions/acceptance/finalize', { method: 'POST', headers: { 'if-match': '"2"' }, body: JSON.stringify({ ...command(), declaredFinalSequence: 0 }) })); expect(final.headers.get('etag')).toBe('"3"'); expect(await final.json()).toMatchObject({ data: { state: 'finalizing', revision: 3 } }); const deleted = await api(request('/api/v1/sessions/acceptance', { method: 'DELETE', headers: { 'if-match': '"3"' } })); expect(deleted.headers.get('etag')).toBe('"4"'); expect(await deleted.json()).toMatchObject({ data: { state: 'deleted', revision: 4 } })
  })
  it('enforces identity, strict routes, preconditions, conflicts, and 64 KiB limits', async () => {
    const api = service(); await create(api); const owner = await api(request('/api/v1/sessions/acceptance', { headers: { authorization: 'Bearer other' } })); const absent = await api(request('/api/v1/sessions/nope', { headers: { authorization: 'Bearer other' } })); expect(owner.status).toBe(404); expect(await owner.json()).toEqual({ error: { code: 'not-found' } }); expect(await absent.json()).toEqual({ error: { code: 'not-found' } }); expect((await create(api, { ...command(), ownerId: 'other' })).status).toBe(400)
    for (const path of ['/api/v1/sessions?owner=x', '/api/v1/sessions/%61', '/api/v1/sessions/acceptance/extra', `/api/v1/sessions/${'a'.repeat(129)}`]) expect((await api(request(path))).status).toBe(404)
    const method = await api(request('/api/v1/sessions/acceptance', { method: 'PUT' })); expect(method.status).toBe(405); expect(method.headers.get('allow')).toBe('GET, DELETE'); const missing = await api(request('/api/v1/sessions/acceptance/start', { method: 'POST' })); expect(missing.status).toBe(428); expect(await missing.json()).toEqual({ error: { code: 'precondition-required' } }); for (const value of ['*', 'W/"0"', '"0", "1"', '"9007199254740992"']) { const invalid = await api(request('/api/v1/sessions/acceptance/start', { method: 'POST', headers: { 'if-match': value } })); expect(invalid.status).toBe(400); expect(await invalid.json()).toEqual({ error: { code: 'invalid-precondition' } }) }
    const length = await api(request('/api/v1/sessions', { method: 'POST', headers: { 'content-length': String(MAX_SESSION_REQUEST_BODY_BYTES + 1) }, body: '{}' })); expect(length.status).toBe(413); secure(length)
  })
  it('maps missing chunks, stale CAS, and exceptions without leaking secrets', async () => {
    const api = service(); await create(api); await api(request('/api/v1/sessions/acceptance/start', { method: 'POST', headers: { 'if-match': '"0"' } })); const missing = await api(request('/api/v1/sessions/acceptance/finalize', { method: 'POST', headers: { 'if-match': '"1"' }, body: JSON.stringify({ ...command(), declaredFinalSequence: 1 }) })); expect(missing.status).toBe(409); expect(await missing.json()).toEqual({ error: { code: 'missing-chunks', missingSequences: [0, 1] } }); const stale = await api(request('/api/v1/sessions/acceptance/chunks', { method: 'POST', headers: { 'if-match': '"0"' }, body: JSON.stringify(chunk()) })); expect(stale.status).toBe(409); expect(await stale.json()).toEqual({ error: { code: 'version-conflict' } }); secure(stale)
    const broken: SessionRepository = { async get(): Promise<StoredSession | undefined> { throw new Error('secret') }, async create() { throw new Error('secret') }, async compareAndSet() { throw new Error('secret') } }; const failure = await create(service(broken)); expect(failure.status).toBe(500); expect(await failure.json()).toEqual({ error: { code: 'internal-error' } }); secure(failure)
  })
})
